[workspace]
changelog_config = "cliff.toml"
allow_dirty = false
repo_url = "https://github.com/EddieDover/praeda"

[[package]]
name = "praeda"
release = true
changelog_update = true
git_tag_enable = true

[[package]]
name = "praeda-godot"
release = false
changelog_update = true
git_tag_enable = false
